# Generated by Django 5.2.1 on 2025-05-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resumedownload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='technical_skills',
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_and_scripting', models.TextField()),
                ('frameworks', models.TextField()),
                ('development_tools', models.TextField()),
                ('web_api_tools', models.TextField()),
                ('operating_system_and_version', models.TextField()),
                ('tools', models.TextField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skill', to='core.employee')),
            ],
        ),
    ]
