# Generated by Django 5.2.1 on 2025-05-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_employee_user_employee_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
