# Generated by Django 5.2.1 on 2025-05-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_employee_password_remove_employee_username'),
    ]

    operations = [
    ]
