# Generated by Django 5.2.1 on 2025-05-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250529_1809'),
    ]

    operations = [
    ]
