# Generated by Django 5.2.1 on 2025-06-04 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Employee', max_length=255),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_skill', to='core.employee'),
        ),
    ]
